name: Test Action

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        run: |
          npm run test
